#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 30 15:20:10 2022

@author: sjcet
"""
print("Armstrong Numbers upto 1000:")
x = 1
y = 1000
while x<=y:
  r = 0
  t = x
  no = 0
  while t>0:
    t = int(t/10)
    no = no + 1
  num = x
  while num>0:
    q = num%10
    p = 1
    i = 0
    while i<no:
      p = p*q
      i = i+1
    r = r+p
    num = int(num/10)
  if r == x:
    print(r)
  x = x+1
